// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface DeleteCompteByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DeleteCompteResult deleted = 1;</code>
   * @return Whether the deleted field is set.
   */
  boolean hasDeleted();
  /**
   * <code>.DeleteCompteResult deleted = 1;</code>
   * @return The deleted.
   */
  ma.projet.grpc.stubs.DeleteCompteResult getDeleted();
  /**
   * <code>.DeleteCompteResult deleted = 1;</code>
   */
  ma.projet.grpc.stubs.DeleteCompteResultOrBuilder getDeletedOrBuilder();
}
